### ISSUE TITLE
Weird error message that appears when I try to use custom paintings for unknown ones

### ISSUE THREAD

**Issue by W-Pangilinan** [andrelikesdogs/sm64-randomizer#31]
![Capture](https://user-images.githubusercontent.com/65684468/92324423-808b2600-f00f-11ea-8f9c-cc6cbc8e4bb7.PNG)

**Comment by andrelikesdogs** [comment]
Sorry for the late reply. Thank you for checking out the project. Please try with these nightly builds:
https://github.com/andrelikesdogs/sm64-randomizer/actions/runs/717465821
