### ISSUE TITLE
unhashable type: list

### ISSUE THREAD

**Issue by FlyingMaster97** [andrelikesdogs/sm64-randomizer#37]
I tried running the program and it gave me this error when i tried randomizing the sm64 rom

**Comment by andrelikesdogs** [comment]
Sorry for the late response. Thank you for trying the randomizer.
This issue involves the usage of randomized paintings when chosing a custom set of paintings.

I assume you were using the newest release - please try these nightly builds, which have this bug fixed:
https://github.com/andrelikesdogs/sm64-randomizer/actions/runs/717465821
