### ISSUE TITLE
macOS application not working, Error loading Python lib

### ISSUE THREAD

**Issue by Openstreetmapler** [andrelikesdogs/sm64-randomizer#60]
When trying to execute the _SM64 Randomizer Generator_, this error message appears in the macOS Terminal:

> [28222] Error loading Python lib '/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python': dlopen: dlopen(/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python, 10): Symbol not found: _futimens
>   Referenced from: /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

**Comment by andrelikesdogs** [comment]
As you'll probably see in the other Pull Request I answered today, please try these [releases](https://github.com/andrelikesdogs/sm64-randomizer/actions/runs/717465821)) - If the error still occurrs please re-open this issue. Thank you!

**Comment by Openstreetmapler** [comment]
The `Python lib not found` error still occurs in version `sm64_randomizer_generator-osx-x64-v0.9.0-754c62e`, but in a different directory.

```
[45358] Error loading Python lib '/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIF4iYHB/libpython3.8.dylib': dlopen: dlopen(/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIF4iYHB/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIF4iYHB/libintl.8.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIF4iYHB/libintl.8.dylib
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...13 completed.
```

Compared to the earlier error message, this one has a different code in the square brackets (45358 instead of 45554) and a different directory and error (`…/_MEIF4iYHB/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin` instead of `…/_MEIM3wJvw/Python, 10): Symbol not found: _futimens`).

**Comment by Openstreetmapler** [comment]
Please re-open the issue since I don’t have the permission or the GitHub experience to do so.
