### ISSUE TITLE
Missing api-ms-win-crt-runtime-l1-1-0.dll on Windows

### ISSUE THREAD

**Issue by SkullCreeper** [andrelikesdogs/sm64-randomizer#7]
For some reason, it doesn't work. It just says that api-ms-win-crt-runtime-l1-1-0.dll is missing from my computer, but, I had it. So, please, create an online website version or fix this bug.

**Comment by Etrainquandt17** [comment]
Did you extract the zip?

**Comment by andre-meyer** [comment]
Hey there! I have an online version now. Sorry for the trouble, it's actually not that trivial to package python programs as standalone applications.

In the meantime, please use the webversion here: https://andre-meyer.github.io/sm64-randomizer/

**Comment by andre-meyer** [comment]
I still want to fix this issue though, can you tell me which Windows version you were running and if you used the GUI or the CLI-Tool?

**Comment by SkullCreeper** [comment]
GUI. 
Windows 8.1.

**Comment by andrelikesdogs** [comment]
Should be fixed with the new releases (will be upcoming soon - use [nightly released](https://github.com/andrelikesdogs/sm64-randomizer/actions/runs/717465821) until then)
