### ISSUE TITLE
Generation fails on Linux

### ISSUE THREAD

**Issue by JKakaofanatiker** [andrelikesdogs/sm64-randomizer#78]
I used the GUI version of the randomizer and a European ROM which is valid.
After clicking "Generate ROM" I get an error message saying:
"expected str, bytes or os.PathLike object, not NoneType"

![image](https://user-images.githubusercontent.com/53398711/135153510-fd2012bb-ac2c-4bf6-91ca-a5cd990e8eea.png)

**Comment by andrelikesdogs** [comment]
Thank you for trying out the randomizer, sorry it didn't work for you. It seems like there was an issue using the Input Path, not something wrong with your file. I'll see if I can figure something out but I'm not running Linux on any of my machines. Could this be an issue with user-permissions?

**Comment by JKakaofanatiker** [comment]
I ran it as root and it still gave me the same error.
The log in the console says that it failed to extend the ROM.
Log: https://pastebin.com/iJ2ma66F
