### ISSUE TITLE
Camera Glitch When Collecting Some Stars

### ISSUE THREAD

**Issue by Etrainquandt17** [andrelikesdogs/sm64-randomizer#8]
Hey! I just wanted to report a glitch so far with the randomizer. When I collected a star in TTM the camera got stuck in place in the sky when using nonstop (stars don't boot you out of the level). And now in HMC when I collect a star in the water the camera gets stuck close to Mario.

**Comment by andre-meyer** [comment]
Thanks for the report. Did you enable disable-starwarp perhaps? This might be an issue with the tweak...

**Comment by Etrainquandt17** [comment]
Yes

**Comment by andre-meyer** [comment]
Thank you! I will work on a fix for that

**Comment by andrelikesdogs** [comment]
Disabled the "disable starwarp" option, as it caused many more issues.
