### ISSUE TITLE
Generation Error: could not find or load spatialindex_c-32.dll

### ISSUE THREAD

**Issue by Zyon134** [andrelikesdogs/sm64-randomizer#85]
![image](https://user-images.githubusercontent.com/63655329/166106344-3415a7b1-c5d9-44a8-b1ab-a88a7210c1ca.png)

could definitely be an issue on my end but i'm not sure. it seems to randomize everything i enabled except for objects

**Comment by Felipezwp** [comment]
I'm also getting this issue on my end
