### ISSUE TITLE
Can't randomize rom hacks

### ISSUE THREAD

**Issue by yourizuring** [andrelikesdogs/sm64-randomizer#9]
It says it can randomize romhacks, but when I try to, I get an error which says 'can't choose from an empty source'.

**Comment by andrelikesdogs** [comment]
Thank you so much for trying it out!

Did you get that error from
the web version or from the downloaded version?
Which version did you download, if you did?
Could you attach the contents of the “sm64_rando_debug.log” file?

Thank you!
